version: 2

sources:
  - name: raw
    schema: gz_raw_data  # Nom du dataset BigQuery
    description: greenweez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez - we have one row per product_id found in each order_id
        columns:
          - name: orders_id
            description: order identifier
            tests:
              - not_null
          - name: pdt_id
            description: product identifier
            tests:
              - not_null

      - name: product
        identifier: raw_gz_product
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        description: shipment_fee by order_id
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique
              - not_null